version: '3.7'
name: codefest2023
services:
  codefest-db:
    image: mongo
    container_name: codefest-db
    ports:
      - "27017:27017" 

  codefest-srv:
    image: codefest:20231012-1629
    container_name: codefest-srv
    ports:
      - "80:3000"
    links:
      - "codefest-db:mongo"
    environment:
      - DB_NAME=codefest2023
      - DB_HOST=codefest-db:27017
      - DEMO_MODE=y
  